monapp/urls.py
# """
# URL configuration for monprojet project.

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/4.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """

# from django.urls import path
# from . import views
# from django.contrib.auth import views as auth_views
# from monapp.views import register,upload_image,user_profile, edit_profile, edit_post, post_detail,delete_post,delete_post_confirm,profile_redirect


# app_name='monapp'
# urlpatterns = [
#     path('', views.home, name='home'),
#     path('register/',register, name='register'),
#     path('upload_image/',upload_image, name='upload_image'),
#     path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
#     path('password-change/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'), name='password_change'),
#     path('profile/<str:username>/', user_profile, name='user_profile'),
#     path('edit_profile/', edit_profile, name='edit_profile'),
#     path('post/edit/<int:post_id>/', edit_post, name='edit_post'),
#     path('post/<int:post_id>/', post_detail, name='post_detail'),
#     path('post/<int:post_id>/delete/confirm/', delete_post_confirm, name='delete_post_confirm'),
#     path('post/<int:post_id>/delete/',delete_post, name='delete_post'),
#     path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
#     path('accounts/profile/', profile_redirect, name='profile_redirect'),
# ]
# monapp/urls.py

from django.urls import path
from . import views
from .views import login_redirect, profile_view, CustomPasswordChangeView, custom_logout #, CustomPasswordResetView,CustomPasswordResetConfirmView
from . import views


app_name = 'monapp'

urlpatterns = [
    path('profile/<str:username>/', views.user_profile, name='user_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('post/edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('accounts/profile/', views.profile_redirect, name='profile_redirect'),
    path('login/redirect/', login_redirect, name='login_redirect'),
    path('profile/<str:username>/', views.profile_view, name='profile_view'),
    path('upload_image/', views.upload_image, name='upload_image'),
    path('password-change/', CustomPasswordChangeView.as_view(), name='password_change'),
    path('logout/', custom_logout, name='logout'),
    # path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    # path('accounts/reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
   
]

monprojet/urls.py
# from django.contrib import admin
# from django.urls import path, include
# from django.conf.urls.static import static
# from django.conf import settings
# from monapp import views as monapp_views

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('monapp/', include('monapp.urls')),
#     path('', monapp_views.home,name='home'),
# ]

#     # path('admin/', admin.site.urls),
#     # path('monapp/', include('monapp.urls')),  # Inclut les URLs de l'application 'monapp'
   
# monprojet/urls.py

from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from monapp import views as monapp_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', monapp_views.home, name='home'),
    path('register/', monapp_views.register, name='register'),
    path('upload_image/', monapp_views.upload_image, name='upload_image'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='change_password.html'), name='password_change'),
    path('monapp/', include('monapp.urls')),  # Including URLs from the monapp application.
    # path('accounts/', include('django.contrib.auth.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monapp/models.py
# Create your models here.
from django.db import models
from django.conf import settings 
from django.contrib.auth.models import AbstractUser

# Modèle pour les posts
# class Post(models.Model):
#     titre = models.CharField(max_length=100)
#     description = models.TextField(blank=True)
#     image = models.ImageField(upload_to='monapp/images/')
#     auteur = models.ForeignKey(User, on_delete=models.CASCADE)
#     date_creation=models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.titre
    
#     class Meta:
#         ordering= ['-date_creation']

# class Profile(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     birth_date = models.DateField(null=True, blank=True)

#     # Vous pouvez ajouter d'autres champs ici si nécessaire

class CustomUser(AbstractUser):
    ROLE_CHOICES = (
        ('subscriber', 'Abonné'),
        ('creator', 'Créateur'),
        ('admin', 'Administrateur'),
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='subscriber')
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.username

class ImagePost(models.Model):
    titre = models.CharField(max_length=255)  # Intitulé du post
    description = models.TextField(blank=True)  # Description de l'image, facultatif
    image = models.ImageField(upload_to='images/')  # Chemin où les images seront stockées
    auteur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # L'auteur de l'image
    date_creation = models.DateTimeField(auto_now_add=True)  # Date de création du post

    def __str__(self):
        return self.titre  # Retourne le titre dans l'interface d'administration

    class Meta:
        ordering = ['-date_creation']  # Ordonne les posts par date de création descendante

monapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import CustomUser
from .models import ImagePost

# Puis ajustez votre formulaire pour utiliser CustomUser
class CustomUserCreationForm(UserCreationForm):
    birth_date = forms.DateField(required=False, help_text='Optional.')   
   
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('birth_date',)


    def save(self, commit=True):
        user = super().save(commit=False)
        user.birth_date = self.cleaned_data['birth_date']
        if commit:
            user.save()
           
        return user



class ImagePostForm(forms.ModelForm):
    class Meta:
        model = ImagePost
        fields = ['titre', 'description', 'image']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username','email', 'first_name', 'last_name', 'birth_date']
        

monapp/views.py
# Create your views here.

from .forms import ImagePostForm
from django.shortcuts import render, redirect,get_object_or_404
from .forms import CustomUserCreationForm,CustomUserChangeForm, ImagePostForm
from django.contrib.auth.models import Group
from .forms import ImagePostForm
from .models import CustomUser, ImagePost
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.urls import reverse
from django.http import Http404
from django.contrib.auth.views import PasswordChangeView #PasswordResetView, PasswordResetConfirmView
from django.views.generic import TemplateView
from django.urls import reverse_lazy


# url = reverse('monapp:profile_view')

# Vue pour la page d'accueil
def home(request):
    context = {}
    # Vous pouvez ajouter plus de contexte si nécessaire, par exemple :
    context['latest_posts'] = ImagePost.objects.all().order_by('-date_creation')[:5]
    return render(request, 'home.html', context)

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            # Assurez-vous que le groupe existe, et ajoutez l'utilisateur au groupe
            group_name = "Abonné"  # Remplacez par le nom de votre groupe
            group, created = Group.objects.get_or_create(name=group_name)
            user.groups.add(group)

            return redirect('home')
    else:
        form = CustomUserCreationForm()

    return render(request, 'register.html', {'form': form})




@login_required
def upload_image(request):
    if request.method == 'POST':
        form = ImagePostForm(request.POST, request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.auteur= request.user
            post.save()
            
            return redirect('monapp:profile_view', username=request.user.username)  # Redirect to a success page
    else:
        form = ImagePostForm()
    return render(request, 'upload_image.html', {'form': form})


def feed(request):
    # Afficher les posts dans l'ordre de création
    posts = ImagePost.objects.all().order_by('-date_creation')
    return render(request, 'feed.html', {'posts': posts})

def user_profile(request, username):
    user = get_object_or_404(CustomUser, username=username)
    posts = ImagePost.objects.filter(auteur=user)
    return render(request, 'user_profile.html', {'user_profile': user, 'posts': posts})


@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('monapp:user_profile', username=request.user.username)
    else:
        form = CustomUserChangeForm(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form})

# Vue pour afficher le profil utilisateur et ses posts
User = get_user_model()

@login_required
def profile_view(request, username):
    # Vérifier que le username correspond à l'utilisateur connecté
    if username != request.user.username:
        raise Http404("Page non trouvée.")

    user = get_object_or_404(User, username=username)
    posts = ImagePost.objects.filter(auteur=user)
    return render(request, 'profile.html', {'user': user, 'posts': posts})

def edit_post(request, post_id):
    post = get_object_or_404(ImagePost, id=post_id, auteur=request.user)
    if request.method == 'POST':
        form = ImagePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('monapp:user_profile', username=request.user.username)
    else:
        form = ImagePostForm(instance=post)
    
    return render(request, 'edit_post.html', {'form': form, 'post': post})

# Vue pour afficher les détails d'un post
def post_detail(request, post_id):
    post = get_object_or_404(ImagePost, id=post_id)
    return render(request, 'post_detail.html', {'post': post})

# Vue pour supprimer un post
# @login_required
# @require_POST
# def delete_post(request, post_id):
#     post = get_object_or_404(ImagePost, id=post_id)
    
#     # Vérifiez que l'utilisateur connecté est l'auteur du post
#     if request.user == post.auteur:
#         post.delete()
#         messages.success(request, "Le post a été supprimé avec succès.")
#         return redirect('home')  # Redirigez vers la page d'accueil ou la liste des posts
#     else:
#         messages.error(request, "Vous n'avez pas la permission de supprimer ce post.")
#         return redirect('monapp:post_detail',post_id=post.id)
    
#     return render(request, 'delete_post.html', {'post': post})
    
# # Vue pour confirmer la suppression d'un post
@login_required
def delete_post(request, post_id):
    post = get_object_or_404(ImagePost, id=post_id)

    if request.method == 'POST':
        # Vérifiez que l'utilisateur connecté est l'auteur du post
        if request.user != post.auteur:
            messages.error(request, "Vous n'avez pas la permission de supprimer ce post.")
            return redirect('home')
        if request.method == 'POST':
            post.delete()
            messages.success(request, "Le post a été supprimé avec succès.")
        return redirect('monapp:profile_view', username=request.user.username)

    return render(request, 'delete_post.html', {'post': post})



@login_required
def profile_redirect(request):
    # Récupérer le nom d'utilisateur de l'utilisateur connecté
    username = request.user.username
    # Rediriger vers la vue de profil de l'utilisateur avec le bon username
    return redirect('user_profile.html', username=username)

@login_required
def login_redirect(request):
    return redirect('monapp:user_profile', username=request.user.username)

class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'change_password.html'
    success_url = '/password_change_done/'  # Redirigez vers une URL appropriée après le changement
    
def password_change_done(request):
    return render(request, 'password_change_done.html')

class PasswordChangeDoneView(TemplateView):
    template_name = 'password_change_done.html'
    
    
def custom_logout(request):
    logout(request)
    messages.info(request, "Vous avez été déconnecté avec succès.")
    return render(request, 'logout.html')

# class CustomPasswordResetView(PasswordResetView):
#     template_name = 'password_reset.html'
#     email_template_name = 'password_reset_email.html'
#     success_url = 'password_reset_confirm.html'
    
    
# class CustomPasswordResetConfirmView(PasswordResetConfirmView):
#     template_name = 'password_reset_confirm.html'  # Spécifiez votre template personnalisé
#     success_url = reverse_lazy('password_reset_done')  # Redirection après la réinitialisation réussie
#     # Vous pouvez personnaliser d'autres aspects si nécessaire

#     def form_valid(self, form):
#         # Logique personnalisée en cas de validation réussie du formulaire
#         messages.success(self.request, "Votre mot de passe a été réinitialisé avec succès.")
#         return super().form_valid(form)

monapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
</head>
<body>
    <header></header>
    <nav>
        
    </nav>
    <main></main>
    <footer></footer>
    
</body>
</html>

monapp/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHANGER|PASSWORD</title>
</head>
<body>
    <header></header>
    <nav><a href="{% url 'home' %}">Retour à la page d'accueil</a></nav>
    <main>
        <section>
            
        
            <h2>CHANGER LE MOT DE PASSE</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Change Password</button>
            </form>

        </section>
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/delete_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SUPPRIMER UN POST</title>
</head>
<body>
    <header></header>
    <nav><a href="{% url 'home' %}">Retour à la page d'accueil</a></nav>
    <main>
        <div class="delete-post">
            <h2>Voulez-vous vraiment supprimer ce post? "{{ post.titre }}" ?</h2>
        
            <form method="post">
              {% csrf_token %}
              <button type="submit">Oui, supprimer ce post</button>
            </form>
        
            <a href="{% url 'monapp:profile_view' username=user.username %}">Non, annuler</a>
          </div>
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header></header>
    <nav>
        <a href="{% url 'home' %}">Retour à la page d'accueil</a>
        <a href="{% url 'monapp:profile_view' username=user.username %}">Voir Profil</a>
        <a href="{% url 'monapp:logout' %}">Se déconnecter</a>
    </nav>
    <main>
        <h2>Édition du Post : {{ post.titre }}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Mettre à jour</button>
  </form>
  <br>
  <br>
  <a href="{% url 'monapp:post_detail' post.id %}">Retour au post</a>
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header></header>
    <nav>
      <a href="{% url 'home' %}">Retour à la page d'accueil</a>
      <a href="{% url 'monapp:profile_view' username=user.username %}">Voir Profil</a>
      <a href="{% url 'monapp:logout' %}">Se déconnecter</a>
      
      

    </nav>
    <main>
          <div class="edit_profile">
            <h1>Éditer le Profil</h1>
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit">Mettre à jour le profil</button>
            </form>
          </div>
 
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/home.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page d'accueil</title>
</head>
<body>
    <header>
       <!-- Lien vers la page d'inscription -->
       <a href='register'>Inscription</a>
       <!-- Lien vers la page de connexion au profil -->
       
       <a href="{% url 'login' %}">Se connecter</a>

    </header>
    <main>
        <section>
            <h1>Bienvenue sur notre site de photographie</h1>
        </section>
        <section>
            {% for post in posts %}
            <h2>{{ post.titre }}</h2>
            <p>{{ post.description }}</p>
            <img src="{{ post.image.url }}" alt="{{ post.titre }}">
            {% endfor %}
        </section>
        <section>
            <p>Découvrez notre collection de photographies et laissez-vous inspirer par les œuvres de nos créateurs.</p>
        </section>

    </main>
    <footer></footer>
</body>
</html>

monapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGIN</title>
</head>
<body>
    <header></header>
    <nav>
        <a href="{% url 'home' %}">Retour à la page d'accueil</a>
    </nav>
    <main>
        <section>
            
            <h2>CONNEXION</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
            <p>Don't have an account? <a href="{% url 'register' %}">Register here</a></p>

        </section>
    </main>
    <footer></footer>
</body>
</html>



    

monapp/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LOGOUT</title>
</head>
<body>
    <header></header>
    <nav>
        <a href="{% url 'home' %}">Retour à la page d'accueil</a>
    </nav>
    <main>
        <section>
           
        <p>Vous avez été déconnecté. Revenez bientôt !</p>
                
       
           

        </section>
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHANGER|PASSWORD</title>
</head>
<body>
    <header></header>
    <nav><a href="{% url 'home' %}">Retour à la page d'accueil</a></nav>
    <main>
        <section>
            
            <h2>Mot de Passe Réinitialisé</h2>
            <p>Votre mot de passe a été réinitialisé avec succès.</p>
            <a href="{% url 'login' %}">Se connecter avec le nouveau mot de passe</a>


        </section>
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHANGER|PASSWORD</title>
</head>
<body>
    <header></header>
    <nav><a href="{% url 'home' %}">Retour à la page d'accueil</a></nav>
    <main>
        <section>
            
        
            <!-- custom_password_reset_email.html -->
            {% autoescape off %}
            Bonjour,

            Veuillez cliquer sur le lien ci-dessous pour réinitialiser votre mot de passe :

            {{ protocol }}://{{ domain }}{% url 'monapp:password_reset_confirm' uidb64=uid token=token %}

            Si vous n'avez pas demandé la réinitialisation de votre mot de passe, veuillez ignorer cet email.

            Merci,
            Votre équipe
            {% endautoescape %}


        </section>
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header></header>
    <nav>
        <a href="{% url 'home' %}">Retour à la page d'accueil</a>
        <a href="{% url 'monapp:profile_view' username=user.username %}">Voir Profil</a>
        <a href="{% url 'monapp:logout' %}">Se déconnecter</a>
    </nav>
    <main>
               
        <div class="post-detail">
            <h1>{{ post.titre }}</h1>
            
            {% if post.image %}
            <img src="{{ post.image.url }}" alt="{{ post.titre }}">
            {% endif %}
            
            <p>{{ post.description }}</p>
            <p>Posté par: {{ post.auteur.username }}</p>
            <p>Date de création: {{ post.date_creation|date:"d/m/Y H:i" }}</p>
            
            <!-- Boutons d'action -->
            {% if user.is_authenticated and user == post.auteur %}
            <a href="{% url 'monapp:edit_post' post.id %}">Éditer ce post</a>
            <!-- Vous pouvez ajouter d'autres actions ici, comme supprimer -->
            <a href="{% url 'monapp:delete_post' post.id %}">Supprimer ce post</a>
            {% endif %}
        </div>

        <!-- Lien pour revenir à la liste des posts ou à la page d'accueil -->
        <a href="{% url 'monapp:profile_view' username=user.username %}">Retour à mon profil</a>
       

    </main>
    <footer></footer>
</body>
</html>

monapp/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ENREGISTRER</title>
</head>
<body>
    <header></header>
    <nav>
      <a href="{% url 'home' %}">Retour à la page d'accueil</a>
      <a href="{% url 'edit_profile' %}">Editer le profil</a>
      <a href="{% url 'logout' %}">Se déconnecter</a>
    </nav>
    <main>
        <section>
           
              <div class="profile-container">
                <h1>Profil de {{ user.username }}</h1>
                <p>Email : {{ user.email }}</p>
                <p>Date de naissance : {{ user.birth_date|date:"d/m/Y" }}</p>
            
                <hr>
            
                <h2>Publications de {{ user.username }}</h2>
                {% for post in posts %}
                  <div class="post">
                    <h3>{{ post.titre }}</h3>
                    {% if post.image %}
                      <img src="{{ post.image.url }}" alt="Image de {{ post.titre }}" class="post-image">
                    {% endif %}
                    <p>{{ post.description }}</p>
                    <p>Posté le {{ post.date_creation|date:"d/m/Y H:i" }}</p>
                    <!-- Ajouter des liens pour éditer et supprimer si l'utilisateur courant est l'auteur du post -->
                    {% if request.user == post.auteur %}
                      <a href="{% url 'edit_post' post.id %}">Éditer</a>
                      <a href="{% url 'delete_post' post.id %}">Supprimer</a>
                    {% endif %}
                  </div>
                {% empty %}
                  <p>Aucune publication n'a été trouvée.</p>
                {% endfor %}
              </div>
            
        </section>
    </main>
    <footer></footer>


</body>
</html>

monapp/templates/upload_image.html
  
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CHARGER UNE IMAGE</title>
</head>
<body>
    <header></header>
    <nav></nav>
    <main>
        <h2>Upload an Image</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Télécharger l'image</button>
            </form>
    </main>
    <footer></footer>
</body>
</html>

monapp/templates/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VOTRE PROFIL</title>
</head>
<body>
    <header></header>
    <nav>
        <a href="{% url 'home' %}">Retour à la page d'accueil</a>
        <a href="{% url 'monapp:profile_view' username=user.username %}">Voir Profil</a>
        <a href="{% url 'monapp:edit_profile'%}">Editer le profil</a>
        <a href="{% url 'password_change' %}">Changer le mot de passe</a>
        <a href="{% url 'upload_image' %}">Télécharger une image</a>
        <a href="{% url 'monapp:logout' %}">Se déconnecter</a>
    </nav>
    <main>
        <h1>Profil de  {{ user_profile.first_name }} {{ user_profile.last_name }}</h1>
        <!-- Afficher les informations du profil -->
            <div class="profile-info">
                <!-- Afficher les informations du profil -->
                <h2>Nom d'utilisateur: {{ user.username }}</h2>
                <p>Email: {{ user.email }}</p>
                <p>Date de naissance: {{ user.birth_date|date:"d/m/Y" }}</p>
            </div>
        <!-- Afficher les publications de l'utilisateur -->
            <div class="user-posts">
                <h2>Publications</h2>
                {% for post in posts %}
                    <div class="post">
                        <h3>{{ post.titre }}</h3>
                        <p>{{ post.description }}</p>
                        {% if post.image %}
                            <img src="{{ post.image.url }}" alt="{{ post.titre }}">
                        {% endif %}  
                        <!-- Détails du post -->
                            <a href="{% url 'monapp:post_detail' post.id %}">Voir les détails du post</a>
                        <!-- Lien pour éditer le post -->  
                        {% if user == post.auteur %}
                            <a href="{% url 'monapp:edit_post' post.id %}">Modifier le post</a>
                        {% endif %}
                    </div>
                    {% empty %}
                         <p>Cet utilisateur n'a pas encore de publications.</p>
                {% endfor %}
            
            </div>

    </main>
    <footer></footer>
</body>
</html>